server:
  port: 8881
spring:
  application:
    name: config-client
  cloud:
    config:
      uri: http://localhost:8888/
      discovery:
        enabled: true
        service-id: config-server
      label: master
      profile: dev
eureka:
  client:
    service-url:
      defaultUrl: http://localhost:8761/eureka

