server:
  port: 8768
spring:
  application:
    name: service-zuul
eureka:
  client:
    service-url:
      defaulfUrl: http://localhost:8761/eureka
zuul:
  routes:
    api-python:
      path: /api-python/**
      serviceId: service-feign
    api-hi:
      path: /api-hi/**
      serviceId: service-ribbon