server:
  port: 8767
spring:
  application:
    name: service-sidecar
eureka:
  client:
    service-url:
      defaultUrl: http://localhost:8761/eureka
sidecar:
  port: 8686
  health-uri: http://localhost:8686/rest/health

