server:
  port: 8888
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ginponson/spring-cloud-demo/
          search-paths: config
          default-label: master
          username:
          password:
eureka:
  client:
    service-url:
      defaultUrl: http://localhost:8761/eureka

